### PR TITLE
Add typescript definitions for the main exports

### PR DESCRIPTION
**Pull request by aarondcohen**
This feature is experimental.  Since I don't use TypeScript, I need someone who does to take a look and verify before i merge this.

### CODE REVIEW

**Comment by lezsakdomi** [comment]
```
node_modules/id128/index.d.ts:65:2 - error TS1169: A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.

65  [Sybol.toStringTag]: string;
    ~~~~~~~~~~~~~~~~~~~

node_modules/id128/index.d.ts:65:3 - error TS2552: Cannot find name 'Sybol'. Did you mean 'Symbol'?

65  [Sybol.toStringTag]: string;
     ~~~~~

  node_modules/typescript/lib/lib.es2015.symbol.d.ts:48:13
    48 declare var Symbol: SymbolConstructor;
                   ~~~~~~
    'Symbol' is declared here.

node_modules/id128/index.d.ts:107:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

107 class Id128Error extends Error {}
    ~~~~~

node_modules/id128/index.d.ts:115:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

115  declare const Ulid: UlidFactory;
     ~~~~~~~

node_modules/id128/index.d.ts:116:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

116  declare const UlidMonotonic: UlidMonotonicFactory;
     ~~~~~~~

node_modules/id128/index.d.ts:117:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

117  declare const Uuid: UuidFactory;
     ~~~~~~~

node_modules/id128/index.d.ts:118:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

118  declare const Uuid1: Uuid1Factory;
     ~~~~~~~

node_modules/id128/index.d.ts:119:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

119  declare const Uuid4: Uuid4Factory;
     ~~~~~~~

node_modules/id128/index.d.ts:120:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

120  declare const Uuid6: Uuid6Factory;
     ~~~~~~~

node_modules/id128/index.d.ts:121:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

121  declare const UuidNil: UuidNilFactory;
     ~~~~~~~

node_modules/id128/index.d.ts:123:2 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

123  declare namespace Exception {
     ~~~~~~~

node_modules/id128/index.d.ts:124:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

124     declare const Id128Error: Id128Error;
        ~~~~~~~

node_modules/id128/index.d.ts:125:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

125     declare const ClockSequenceOverflow: ClockSequenceOverflow;
        ~~~~~~~

node_modules/id128/index.d.ts:126:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

126     declare const InvalidBytes: InvalidBytes;
        ~~~~~~~

node_modules/id128/index.d.ts:127:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

127     declare const InvalidEncoding: InvalidEncoding;
        ~~~~~~~

node_modules/id128/index.d.ts:128:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

128     declare const InvalidEpoch: InvalidEpoch;
        ~~~~~~~

node_modules/id128/index.d.ts:129:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

129     declare const UnsupportedVersion: UnsupportedVersion;
        ~~~~~~~

```

**Comment by aarondcohen** [comment]
It all compiles for me locally.  Please check that it actually integrates properly.  Also, I'm worried I'm bleeding types into the global namespace.  any guidance is much appreciated.

**Comment by aarondcohen** [comment]
@patarapolw: Seriously, thank you for the feedback.   i've been waiting for comments to know if i can merge this since i don't write typescript.  i'll review and push a modification in the next few days.

**Comment by aarondcohen** [comment]
@patarapolw  2 thoughts:
1. the use of `unknown` in this code seems equivalent to saying: "any value will do because i won't inspect it anyway".  i'm not sure I want that because it limits the ability to augment the options in the future.  by keeping it an optional `{}`, i can guarantee an upgradable interface.  I want the type system to say: "give me nothing or any named parameters you wish.  i'll select out what's important."  in this regard, does `{}` create any type issues? 
1.  i want to make sure i don't leak any of the intermediate types to to limit confusion and allow for flexibility in any future rearchitecting.  how does wrapping the file in `declare module "id128" { ... }` affect the visibility of the intermediate types?  what would the import line look like with this change?

**Comment by patarapolw** [comment]
> `unknown` vs `{}`

`{}` may cause conflict in your JavaScript, unless you use `// @ts-check` in your JavaScript code in VSCode (not sure about WebStorm).

`unknown` instead will prompt `// @ts-check` users to declare type (via JSDoc `/** @type {*} */`).

Otherwise, I believe it is no different. It behaves almost the same for end-users.

> how does wrapping the file in `declare module "id128" { ... }` affect the visibility of the intermediate types? what would the import line look like with this change?

`declare module "id128" { ... }` just means that you use your own `declaration.d.ts`, without an `@types/` folder. Nothing more.

However, if you publish your own `index.d.ts`, there will be no `declare module`.

**Comment by aarondcohen** [comment]
i have verified the type file locally using visual studio code.  i will clean this up and merge it shortly.

**Pull request merged**
